name: fast_food
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  hydrated_bloc: ^10.1.1
  image_picker: ^1.2.0
  lottie: ^3.3.2
  model_viewer_plus: ^1.9.3
  path_provider: ^2.1.5
  provider: ^6.1.0
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.0+1
  

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_foreground: "assets/logo/logo_foreground.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/banner/
    - assets/detail/
    - assets/icon/
    - assets/logo/
    - assets/splash/
    - assets/test/
    - assets/lottie/
    - assets/3dModel/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
